
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class Players : Luban.BeanBase
{
    public Players(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["attr_hp"].IsNumber) { throw new SerializationException(); }  AttrHp = _buf["attr_hp"]; }
        { if(!_buf["attr_atk"].IsNumber) { throw new SerializationException(); }  AttrAtk = _buf["attr_atk"]; }
        { if(!_buf["gold"].IsNumber) { throw new SerializationException(); }  Gold = _buf["gold"]; }
        { if(!_buf["gem"].IsNumber) { throw new SerializationException(); }  Gem = _buf["gem"]; }
        { if(!_buf["level"].IsNumber) { throw new SerializationException(); }  Level = _buf["level"]; }
    }

    public static Players DeserializePlayers(JSONNode _buf)
    {
        return new Players(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 属性
    /// </summary>
    public readonly int AttrHp;
    /// <summary>
    /// 属性
    /// </summary>
    public readonly int AttrAtk;
    /// <summary>
    /// 金币
    /// </summary>
    public readonly int Gold;
    /// <summary>
    /// 钻石
    /// </summary>
    public readonly int Gem;
    /// <summary>
    /// 等级
    /// </summary>
    public readonly int Level;
   
    public const int __ID__ = 1171085714;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "attrHp:" + AttrHp + ","
        + "attrAtk:" + AttrAtk + ","
        + "gold:" + Gold + ","
        + "gem:" + Gem + ","
        + "level:" + Level + ","
        + "}";
    }
}

}
