
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.players
{
public partial class TbPlayers
{
    private readonly System.Collections.Generic.Dictionary<int, Players> _dataMap;
    private readonly System.Collections.Generic.List<Players> _dataList;
    
    public TbPlayers(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Players>();
        _dataList = new System.Collections.Generic.List<Players>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Players _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Players.DeserializePlayers(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Players> DataMap => _dataMap;
    public System.Collections.Generic.List<Players> DataList => _dataList;

    public Players GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Players Get(int key) => _dataMap[key];
    public Players this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}
